### PR TITLE
Adding setServiceURL to compliment getServiceURL

### PR DESCRIPTION
**Pull request by ilatif**
I saw that there is `getServiceURL` which is being used quite some time in code. But there was no setter method for `$this->service_url. So I created one.

### CODE REVIEW

**Comment by kamranahmedse** [comment]
@ilatif since, for now, library just supports Google's Geocoding API and there cannot be any other service URLs other than Google's, so there is no point in exposing the setter method to set the service URL.

**Comment by ilatif** [comment]
@kamranahmedse It's first time in my life I have heard that a setter method will break the functionality. Anyways, I respect your opinion.


Thanks.

**Comment by kamranahmedse** [comment]
@ilatif glad that I was the one to break it to you :)
Actually, the library uses Google's Geocoding API and each of the method in it is written keeping in view how to interact with it. And so user is not allowed to change the URL. Except one thing that can be done is providing a method to change that protocol later on, once the object has been instantiated.

**Comment by ilatif** [comment]
@kamranahmedse: I totally agree. But same thing goes for `getServiceURL` as well. Why would someone need to access which Geocoding API are you using? :smile:. `getServiceURL` method should be `private` in this case.

Also, `getter` and `setter` methods shouldn't be used in class definition itself to get or set properties. While you are in class you have access to all private data members so to avoid method call overhead private properties are accessed directly in class definition. :-).

Thanks.

**Pull request closed without merging**
